package zadanie05;

/**
 * Produkty spożywcze.
 */
public enum Produkt {
    CUKIER, MAKA_PSZENNA, MAKA_RAZOWA, MASLO, WODA, SOL, DROZDZE,
    PROSZEK_DO_PIECZENIA, CUKIER_PUDER, MLEKO, OLEJ_ROSLINNY,
    CUKIER_WANILIOWY, MAKA_ZIEMNIACZANA, TWAROG, RODZYNKI, MARGARYNA,
}
